# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89483481dee165f4cab575156785c21c4fb8db7ca13d8c2807667db6ccf52f7bfd53365f5f36b34fc5cbdf9da04380b8705fc90b8daeae838c2cce62236cf56d

test:
  secret_key_base: c124971ab16ffa5f9f5f51117daaedb284fd08656d7beb34120f79001e8777de5cb33f7c614d4b0b4e8504ce78dc165213f47a1670751808375dffd17b96541b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
